---
language: objective-c

os:
  - osx

osx_image: xcode7

install:
    - sudo -H easy_install pip
    - sudo -H pip install -I ansible==1.9.4
    - mkdir -p /tmp/roles
    - "{ echo '[defaults]'; echo 'roles_path = ../:/tmp/roles'; } >> ansible.cfg"

script:
  - "ansible-playbook -i tests/inventory tests/travis.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/travis.yml --connection=local"
